### PR TITLE
Many changes

### PR DESCRIPTION
**Pull request by TheTechRobo**
This is the version I'll be using in my calculator.

- Switch the README to markdown, it's the new standard, include better formatting.
- Change `not valid` (or `not a valid`) to `invalid`.
- Bump version to 0.2.
- Add mulkieran and TheTechRobo to the author param in setup.py
- Switch from raising`Exception` to `ValueError` so it's a little easier to catch.

I think that's it, enjoy! :D

### CODE REVIEW

**Comment by TheTechRobo** [comment]
Sorry, there are conflicts. You'll have to resolve them, but I don't think they're very complex

**Comment by TheTechRobo** [comment]
Fixed the conflicts. :)

**Comment by TheTechRobo** [comment]
You can always take my changes in the future if you want.

**Comment by mulkieran** [comment]
Sorry, I got confused because this is only a fork of somebody else's work. I think I thought I had seen it because I was watching the repo of which this is a fork. If you let me  know precisely what you're trying to do, I could probably accomodate it.

**Comment by TheTechRobo** [comment]
Yeah, it's fine. They weren't huge changes. The PR was created back when I was naïve about pull requests. 🙂

**Pull request closed without merging**
